### ISSUE TITLE
GPS offset setting improvement suggestion

### ISSUE THREAD

**Issue by CommanderPirx** [LordTylus/SE-Torch-Plugin-ALE-GpsRoulette#1]
(as seen here: https://discord.com/channels/230191591640268800/360599679714590743/778395050685759509)

The idea is to basically replace the fixed offset distance for the GPS point with two configurable values - a minimal and a maximal one. And then the GPS point would just appear a random value between those, in a random direction. It would make the feature better fulfill its purpose of making the exact position of the player that's being searched for more vague for the searching party. That's all. Cheers. 👌

**Comment by LordTylus** [comment]
Added in 1.0.0.1
