### ISSUE TITLE
Additional filtering step for buying GPS feature suggestion

### ISSUE THREAD

**Issue by CommanderPirx** [LordTylus/SE-Torch-Plugin-ALE-GpsRoulette#2]
(as seen here: https://discord.com/channels/230191591640268800/360599679714590743/778386351879487498)

It would be better (in some cases) if the possibility of buying the GPS points was behind a configurable filter as well (certain amount of PCU for example) - not just the possibility of being found. So that you can only buy GPS points once you have a certain amount of PCU. This way there could be no situation where someone could search for others, while being without the risk of being found out themselves. Of course this should just be a togglable option so that admin could choose to use it or not.

**Comment by LordTylus** [comment]
Since I am not starting to think of filters myself Ill only implement the two things we talked about:

- Min PCU a player must have to be able to buy 
- Min time the player must be online before being able to buy

**Comment by LordTylus** [comment]
Added 1.0.0.2
