### ISSUE TITLE
Delay notification sent to online player when their GPS is purchased

### ISSUE THREAD

**Issue by Isadorious** [LordTylus/SE-Torch-Plugin-ALE-GpsRoulette#4]
The ability to delay the notification sent to a player when their GPS is purchased by X seconds. This is to stop players for jumping away immediately after their location has been purchased and help with PVP more.

**Comment by LordTylus** [comment]
Added in v1.0.0.6

```
13:40:29.8591 [INFO]   GpsRouletteCommands: Player LordTylus bought GPS Location X: -13157.4568160529 Y: -53807.0381841175 Z: -25995.9934618551 of Player Imperial Sappers CEO
13:40:29.8591 [INFO]   Chat:  (to LordTylus): Purchase successful!
13:40:29.8591 [INFO]   CommandManager: Player LordTylus ran command '!gps buy random'
13:41:29.1936 [INFO]   GpsRoulettePlugin: Identity 144115188075855900 Imperial Sappers CEO was Notified about their GPS being bought!
```

Example of Logs when GPS were bought and Notified 60 Seconds later.

Note however. The notifications wont be sent when the server shuts down or otherwise restarts.
